workflows:
  ios_forescore:
    name: iOS ForeScore -> TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 120

    integrations:
      app_store_connect: codemagic

    environment:
      node: latest

      vars:
        APP_STORE_APPLE_ID: "1555555551"
        BUNDLE_ID: "xyz.forescore.app"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "xyz.forescore.app"

    scripts:
      - name: Install JS dependencies
        script: |
          npm config set production false
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS project
        script: |
          ./node_modules/.bin/cap sync ios

      # NEW: locate the actual workspace/project paths present in CI
      - name: Locate Xcode workspace
        script: |
          set -e
          echo "Listing ios directory:"
          ls -la ios || true
          echo "Searching for workspace:"
          find ios -maxdepth 3 -name "*.xcworkspace" -print || true
          echo "Searching for xcodeproj:"
          find ios -maxdepth 3 -name "*.xcodeproj" -print || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Apply signing profiles
        script: |
          xcode-project use-profiles

      # NEW: auto-detect workspace path so builds don't break if the folder name differs
      - name: Build IPA
        script: |
          set -euo pipefail
          WORKSPACE="$(find ios -maxdepth 3 -name '*.xcworkspace' | head -n 1)"
          if [ -z "$WORKSPACE" ]; then
            echo "No .xcworkspace found. Contents of ios/:"
            ls -la ios || true
            find ios -maxdepth 3 -name '*.xcodeproj' -print || true
            exit 1
          fi
          echo "Using workspace: $WORKSPACE"
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
