workflows:
  ios_forescore:
    name: iOS ForeScore -> TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      node: latest
      groups:
                - ForeScore

      vars:
        APP_STORE_APPLE_ID: "6758790249"
        BUNDLE_ID: "xyz.forescore.app"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "xyz.forescore.app"

    scripts:
      - name: Install JS dependencies
        script: |
          npm config set production false
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Sync Capacitor iOS project
        script: |
          ./node_modules/.bin/cap sync ios

      # NEW: locate the actual workspace/project paths present in CI
      - name: Locate Xcode workspace
        script: |
          set -e
          echo "Listing ios directory:"
          ls -la ios || true
          echo "Searching for workspace:"
          find ios -maxdepth 3 -name "*.xcworkspace" -print || true
          echo "Searching for xcodeproj:"
          find ios -maxdepth 3 -name "*.xcodeproj" -print || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Apply signing profiles
        script: |
          xcode-project use-profiles

      - name: Bump iOS build number
        script: |
          # Example: set build number to current Unix timestamp
          BUILD_NUM=$(date +%s)
          echo "Setting CFBundleVersion to $BUILD_NUM"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUM" ios/App/App/Info.plist

      # NEW: auto-detect workspace path so builds don't break if the folder name differs
      - name: Build IPA
        script: |
          set -euo pipefail

          # Prefer the CocoaPods workspace (includes Pods)
          if [ -d "ios/App/App.xcworkspace" ]; then
            WORKSPACE="ios/App/App.xcworkspace"
          else
            WORKSPACE="$(find ios -maxdepth 4 -name '*.xcworkspace' \
              | grep -v 'project.xcworkspace' \
              | head -n 1)"
          fi
          
          mkdir -p build/ios.ipa

          echo "Using workspace: $WORKSPACE"

          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --ipa-directory build/ios/ipa

      - name: Verify IPA exists
        script: |
          set -e
          echo "Verifying IPA in build/ios/ipa:"
          ls -la build/ios/ipa
          if ! ls build/ios/ipa/*.ipa 1> /dev/null 2>&1; then
            echo "No IPA file found in build/ios/ipa"
            exit 1
          fi
          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log


    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
