workflows:
ios_forescore:
  name: iOS ForeScore -> TestFlight
  instance_type: mac_mini_m2
  max_build_duration: 120

  environment:
    node: latest
    vars:
      # REQUIRED: numeric Apple ID from App Store Connect (App Information)
      APP_STORE_APPLE_ID: "1555555551"

      # REQUIRED: must match your Xcode bundle id + App Store Connect bundle id
      BUNDLE_ID: "xyz.forescore.app"

      # Typical Capacitor defaults (adjust if your project differs)
      XCODE_WORKSPACE: "ios/App/App.xcworkspace"
      XCODE_SCHEME: "App"

    ios_signing:
      distribution_type: app_store
      bundle_identifier: "xyz.forescore.app"

  integrations:
    # Must match the name of your App Store Connect integration in Codemagic UI
    app_store_connect: codemagic

  scripts:
    - name: Install JS deps
      script: |
        set -euo pipefail
        npm ci

    - name: Build web
      script: |
        set -euo pipefail
        npm run build

    - name: Sync Capacitor iOS
      script: |
        set -euo pipefail
        npx cap sync ios

    - name: CocoaPods install
      script: |
        set -euo pipefail
        cd ios/App
        pod install

    - name: Apply signing profiles
      script: |
        set -euo pipefail
        xcode-project use-profiles

    - name: Increment build number
      script: |
        set -euo pipefail
        cd "$CM_BUILD_DIR/ios/App"
        LATEST=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID" || echo "")
        if [ -z "$LATEST" ]; then
          NEXT="$BUILD_NUMBER"
        else
          NEXT=$((LATEST + 1))
        fi
        agvtool new-version -all "$NEXT"

    - name: Build IPA
      script: |
        set -euo pipefail
        cd "$CM_BUILD_DIR/ios/App"
        xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

  artifacts:
    - ios/App/build/ios/ipa/*.ipa
    - /tmp/xcodebuild_logs/*.log

  publishing:
    app_store_connect:
      auth: integration
      submit_to_testflight: true