workflows:
ios-forescore:
  name: iOS ForeScore (Capacitor) -> TestFlight
  max_build_duration: 120
  instance_type: mac_mini_m2

  integrations:
    # This must match the App Store Connect API key name you set in Codemagic UI
    app_store_connect: codemagic

  environment:
    node: latest

    # Uses Codemagic-managed signing identities/profiles
    ios_signing:
      distribution_type: app_store
      # IMPORTANT: set this to your REAL bundle id used by the Xcode project
      # Example from your earlier package was "xyz.forescore.app"
      bundle_identifier: xyz.forescore.app

    vars:
      # Required for build number increment via App Store Connect
      # Find in App Store Connect -> App Information (Apple ID)
      APP_STORE_APPLE_ID: 1555555551

      # Capacitor default workspace/scheme (common defaults):
      XCODE_WORKSPACE: "ios/App/App.xcworkspace"
      XCODE_SCHEME: "App"

    # Optional but recommended for deterministic installs
    npm: true

  triggering:
    events:
      - push
    branch_patterns:
      - pattern: main
        include: true
        source: true

  scripts:
    - name: Install npm dependencies
      script: |
        set -e
        npm ci

    - name: Build web app
      script: |
        set -e
        npm run build

    - name: Sync Capacitor iOS project
      script: |
        set -e
        npx cap sync ios

    - name: Install CocoaPods
      script: |
        set -e
        cd ios/App
        pod install

    - name: Apply code signing profiles to Xcode project
      script: |
        set -e
        xcode-project use-profiles

    - name: Increment build number (from App Store Connect)
      script: |
        set -e
        cd "$CM_BUILD_DIR/ios/App"

        LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
        if [ -z "$LATEST_BUILD_NUMBER" ]; then
          # If no builds exist yet, fall back to Codemagic build number
          UPDATED_BUILD_NUMBER=$BUILD_NUMBER
        else
          UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
        fi

        agvtool new-version -all "$UPDATED_BUILD_NUMBER"

    - name: Build IPA for distribution
      script: |
        set -e
        cd "$CM_BUILD_DIR/ios/App"

        xcode-project build-ipa \
          --workspace "$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME"

  artifacts:
    - ios/App/build/ios/ipa/*.ipa
    - /tmp/xcodebuild_logs/*.log
    - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

  publishing:
    app_store_connect:
      auth: integration
      submit_to_testflight: true

      # Optional: push to specific TestFlight groups (must match group names exactly)
      # beta_groups:
      #   - Internal Testers

    email:
      recipients:
        - you@example.com
      notify:
        success: true
        failure: true
