-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0GMbzq5UIAj1EHOb
OFfI0RJFmis0Uj+uiUrMD0g22eigCgYIKoZIzj0DAQehRANCAAStIVHbjTRqfg1Q
w8B2OlbbV7mF/3WiZE7vFTgVTru1urHUoCT//Zh50NaJnajXiXXiVyP4GsgvwOTt
We0LwE4z
-----END PRIVATE KEY-----