import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";

interface LegalDialogsProps {
  showTerms: boolean;
  showPrivacy: boolean;
  onOpenChange: (type: 'terms' | 'privacy', open: boolean) => void;
}

export default function LegalDialogs({ showTerms, showPrivacy, onOpenChange }: LegalDialogsProps) {
  return (
    <>
      {/* Terms of Service Dialog */}
      <Dialog open={showTerms} onOpenChange={(open) => onOpenChange('terms', open)}>
        <DialogContent className="max-w-4xl max-h-[80vh]" data-testid="dialog-terms">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold text-gray-900">Terms of Service</DialogTitle>
            <DialogDescription className="text-gray-600">
              Please read our Terms of Service carefully
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-96 pr-4" data-testid="scroll-terms">
            <div className="space-y-4 text-sm text-gray-800">
              <p>
                Welcome to ForeScore. ForeScore is a service of danoNano, LLC (dba ForeScore) ("ForeScore," "we," "our," or "us"). These Terms of Service ("Terms") govern your access to and use of the ForeScore web and mobile applications, websites, and related services (collectively, the "Service"). By accessing or using the Service, you agree to these Terms. If you do not agree, do not use the Service.
              </p>

              <section>
                <h3 className="font-semibold text-lg mb-2">Eligibility & Accounts</h3>
                <p>
                  You must be at least 13 years old (or the minimum age of digital consent in your country) to use the Service. If your jurisdiction requires you to be older to enter into a binding contract or to participate in golf-related side games or wagering-adjacent activities, you must meet that higher age threshold. You are responsible for the accuracy of your account information and all activity under your account. If you use a third-party login (e.g., Google, Apple, Facebook), you must comply with that provider's terms and you authorize us to access certain profile information. Keep your credentials secure; you are responsible for any use of your account.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">What ForeScore Does (and Doesn't Do)</h3>
                <p>
                  ForeScore provides tools to organize golf groups, track side games (such as "Sacramento (916)") and other scoring formats, and calculate suggested payouts or point allocations based on your group's inputs and rules. The Service is intended purely as a scoring and organizational utility for recreational golf; it is not a gambling or gaming operator.
                </p>
                <p className="mt-2 font-medium">No Gambling or Real-Money Gaming.</p>
                <p>
                  ForeScore does not offer, enable, or process real-money gambling, wagering, lotteries, sweepstakes, or contests of chance. The Service does not handle deposits, withdrawals, bets, or prize payments, and does not provide any mechanism to transfer money or value between users. Any real-world settlements, payments, or exchanges among players occur entirely outside the Service and at users' sole discretion and risk. You are responsible for complying with all laws and regulations that apply to any activity you choose to conduct outside the Service.
                </p>
                <p className="mt-2 font-medium">Utility Only.</p>
                <p>
                  Suggested scores, points, handicaps, or payouts generated by the Service are for informational and entertainment purposes only. We do not guarantee accuracy, fairness, or compliance with any governing body's handicapping or competition rules, and you should independently verify any calculations that matter for your group.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">User-Generated Content & Conduct</h3>
                <p>
                  You may submit content such as profile names, group names, game configurations, messages, and scores ("User-Generated Content" or "UGC"). You retain rights to your UGC, but you grant ForeScore a non-exclusive, worldwide, royalty-free, sublicensable license to host, store, display, reproduce, modify, and adapt it solely as needed to operate, provide, secure, and improve the Service.
                </p>
                <p className="mt-2">You agree not to:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>Upload or share unlawful, infringing, defamatory, harassing, hateful, discriminatory, pornographic, or misleading content.</li>
                  <li>Use the Service to threaten, bully, or abuse others, or to promote self-harm, illegal activity, or hate.</li>
                  <li>Spam, scrape, reverse engineer, or interfere with the Service or its security.</li>
                  <li>Attempt to circumvent technical protections, usage limits, or access controls.</li>
                </ul>
                <p className="mt-2">
                  We may remove content or suspend or terminate accounts that violate these Terms, our policies, or applicable law. We may also take reasonable steps to moderate UGC, including automated or manual review, but we do not promise to monitor all activity and you remain responsible for your own conduct.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Marketing Communications</h3>
                <p>
                  By creating an account, you consent to receive marketing and promotional communications from ForeScore, including emails, push notifications, and other messages. You may opt out at any time by following unsubscribe instructions in those messages or by adjusting your notification or device settings. Opting out of marketing will not affect essential service communications (e.g., transactional or security notices).
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Privacy</h3>
                <p>
                  Your use of the Service is also governed by our Privacy Policy, which explains what information we collect, how we use and share it, the legal bases for processing, and your choices regarding data access, correction, deletion, and marketing preferences. Please review the Privacy Policy carefully before using the Service. Where required by law, we will honor your privacy rights requests and provide appropriate data protection disclosures.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">License & Intellectual Property</h3>
                <p>
                  Subject to these Terms, we grant you a limited, personal, non-exclusive, non-transferable, revocable license to use the Service for its intended purpose on devices you own or control. All rights, title, and interest in and to the Service (excluding UGC) remain with ForeScore and its licensors, including all software, text, graphics, logos, trademarks, and other content. You may not copy, modify, distribute, sell, or lease any part of the Service, nor may you reverse engineer or attempt to extract source code, except as expressly permitted by law.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Payments, Subscriptions & Trials (if offered)</h3>
                <p>If we offer paid features, in-app purchases, or subscriptions, the following apply:</p>
                <p className="mt-2 font-medium">Pricing & Billing.</p>
                <p>We will disclose pricing, billing frequency, and, where applicable, the free trial period and any introductory offers at the point of purchase in the app and/or on the Service. Any taxes or fees will be disclosed where required.</p>
                <p className="mt-2 font-medium">Subscriptions & Auto-Renewal.</p>
                <p>If you purchase a subscription, it may auto-renew at the end of each billing period unless canceled at least 24 hours before the end of the then-current period, as described in the purchase flow. You can manage or cancel your subscription through your device account settings (e.g., Apple ID subscription settings) or as otherwise described in the app.</p>
                <p className="mt-2 font-medium">Free Trials.</p>
                <p>If a free trial is offered, we will specify its duration and what happens when it ends. Unless you cancel before the trial ends, your subscription may convert to a paid plan as disclosed at sign-up.</p>
                <p className="mt-2 font-medium">Refunds.</p>
                <p>Where purchases are made through a platform provider (such as Apple's App Store), that provider's refund policies apply, and you may need to request refunds directly from them. For purchases made directly via our website or other channels, our own refund policy (if any) will apply, and we will describe it clearly at the time of purchase. Nothing in these Terms limits any mandatory refund or cancellation rights you may have under applicable law.</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Third-Party Services</h3>
                <p>
                  The Service may link to or integrate with third-party tools or services (e.g., chat platforms, analytics providers, payment processors). These third-party services are not under our control, and ForeScore is not responsible for their content, policies, or practices. Your use of any third-party service is at your own risk and may be governed by that third party's terms and privacy policy.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Disclaimers</h3>
                <p className="uppercase">
                  THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, AVAILABILITY, OR RELIABILITY. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED.
                </p>
                <p className="mt-2">
                  Some jurisdictions do not allow limitations on implied warranties, so the above may not fully apply to you. In that case, the duration of any required warranties will be limited to the minimum period permitted by law.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Limitation of Liability</h3>
                <p className="uppercase">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, FORESCORE AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                </p>
                <p className="mt-2 uppercase">
                  TO THE EXTENT PERMITTED BY LAW, OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE 12 MONTHS PRECEDING THE CLAIM OR (B) USD $50.
                </p>
                <p className="mt-2">
                  Some jurisdictions do not allow certain limitations of liability; in those cases, these limitations will apply to you only to the extent permitted by applicable law.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Indemnification</h3>
                <p>
                  You agree to indemnify, defend, and hold harmless ForeScore and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or related to: (a) your UGC; (b) your use or misuse of the Service; or (c) your violation of these Terms or any applicable law or regulation.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Suspension & Termination</h3>
                <p>
                  We may suspend or terminate your access to the Service, or remove UGC, if we reasonably believe you have violated these Terms, our policies, or applicable law, or if we need to do so to protect the Service or other users. Where reasonable, we will attempt to provide notice of material suspensions or terminations. You may stop using the Service and close your account at any time through your account settings or by contacting us.
                </p>
                <p className="mt-2">
                  Sections relating to intellectual property, payments and subscriptions, disclaimers, limitations of liability, indemnification, governing law, and dispute resolution will survive termination.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Changes to the Service and to These Terms</h3>
                <p>
                  We may update or modify the Service from time to time, including by adding or removing features. We may also update these Terms. If changes are material, we will notify you through the Service, by email, or by other reasonable means. Changes take effect when posted unless otherwise stated. Your continued use of the Service after changes become effective means you accept the revised Terms. If you do not agree, you must stop using the Service.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Governing Law & Jurisdiction</h3>
                <p>
                  These Terms are governed by the laws of the State of Arizona, USA, without regard to its conflict-of-law rules, except where applicable law in your country requires a different governing law for consumer contracts. Any disputes arising from or relating to these Terms or the Service will be brought exclusively in the state or federal courts located in Maricopa County, Arizona, USA, and you consent to the personal jurisdiction of those courts, except where applicable law gives you the right to bring claims in your local courts.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">Contact & Support</h3>
                <p>If you have questions, concerns, or support requests regarding the Service or these Terms, you can contact us at:</p>
                <p className="mt-2">
                  Email: support@forescore.xyz<br />
                  Postal: danoNano, LLC, 2447 E Fremont Rd, Phoenix, AZ 85042, USA
                </p>
                <p className="mt-2">
                  We will make reasonable efforts to respond to support requests within a commercially reasonable time.
                </p>
              </section>

              <div className="text-xs text-gray-500 mt-6 pt-4 border-t">
                <p>Last updated: September 25, 2025</p>
              </div>
            </div>
          </ScrollArea>
        </DialogContent>
      </Dialog>

      {/* Privacy Policy Dialog */}
      <Dialog open={showPrivacy} onOpenChange={(open) => onOpenChange('privacy', open)}>
        <DialogContent className="max-w-4xl max-h-[80vh]" data-testid="dialog-privacy">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold text-gray-900">Privacy Policy</DialogTitle>
            <DialogDescription className="text-gray-600">
              Learn how we collect, use, and protect your information
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-96 pr-4" data-testid="scroll-privacy">
            <div className="space-y-4 text-sm text-gray-800">
              <p>
                This Privacy Policy explains how ForeScore, a service of danoNano, LLC (dba ForeScore) ("ForeScore," "we," "our," or "us"), collects, uses, and shares information when you use our websites, web apps, mobile apps, and related services (collectively, the "Service"). By using the Service, you agree to the practices described in this Privacy Policy.
              </p>

              <section>
                <h3 className="font-semibold text-lg mb-2">1. Information We Collect</h3>
                <p>We may collect the following types of information:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li><strong>Account Information:</strong> Name, email address, password or other login credentials, and any identifiers you provide when creating an account or signing in via third-party services (such as Google or Apple).</li>
                  <li><strong>Profile & Gameplay Data:</strong> Information you add to your profile, your groups and games, game configurations, scores entered, and related in-app activity.</li>
                  <li><strong>Device & Usage Data:</strong> Technical information such as IP address, device type, operating system, app version, language, time zone, and information about how you interact with the Service (e.g., screens viewed, features used, session duration).</li>
                  <li><strong>Cookies & Similar Technologies:</strong> We use cookies, local storage, and similar technologies to remember your preferences, keep you signed in, and help us understand how the Service is used.</li>
                  <li><strong>Communications:</strong> Information you provide when you contact us for support, respond to surveys, or participate in promotions, including the content of messages and your contact details.</li>
                </ul>
                <p className="mt-2">
                  We do not knowingly collect personal data from children under 13 (or under the digital age of consent in your jurisdiction). If we learn that we have collected such data, we will take steps to delete it.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">2. How We Use Information</h3>
                <p>We use the information we collect for the following purposes:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li><strong>Provide the Service:</strong> To create and manage accounts, enable gameplay tracking and group features, and operate core functionality of the Service.</li>
                  <li><strong>Improve & Personalize:</strong> To understand how the Service is used, fix bugs, develop new features, and personalize content, settings, and recommendations.</li>
                  <li><strong>Communications:</strong> To send you service-related messages (such as account notices, security alerts, and changes to our terms or policies) and, where permitted by law, marketing or promotional messages about ForeScore. You can opt out of marketing at any time (see Section 7).</li>
                  <li><strong>Security & Fraud Prevention:</strong> To protect the Service and our users, detect and prevent abuse, fraud, or other harmful activity, and enforce our Terms of Service.</li>
                  <li><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, legal processes, and law enforcement requests.</li>
                </ul>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">3. Sharing of Information</h3>
                <p>We do not sell your personal data. We may share information in the following situations:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li><strong>Service Providers:</strong> With trusted third-party vendors who perform services on our behalf, such as hosting, analytics, email delivery, customer support, or payment processing. These providers are permitted to use your information only as needed to provide services to us.</li>
                  <li><strong>Legal & Safety:</strong> When we believe in good faith that disclosure is reasonably necessary to comply with a law, regulation, legal process, or governmental request, or to protect the rights, property, or safety of ForeScore, our users, or others.</li>
                  <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, financing, reorganization, or sale of all or part of our business or assets. In such cases, we will take reasonable steps to ensure your privacy rights are respected.</li>
                  <li><strong>With Your Consent:</strong> We may share information for other purposes when you explicitly direct or consent to that sharing.</li>
                </ul>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">4. Analytics & Cookies (including Google Analytics)</h3>
                <p>We use analytics tools (such as Google Analytics) to help us understand how users find and use ForeScore, measure the performance of the Service, and improve user experience.</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>Analytics tools may collect information such as device type, approximate location (based on IP address), pages or screens viewed, time spent in the app, and interactions with features.</li>
                  <li>We configure analytics tools so that data is reported in aggregate and is not used by us to directly identify you as an individual.</li>
                  <li>You can manage cookies and similar technologies through your browser or device settings. Components such as the Google Analytics Opt-out Browser Add-on may allow you to limit certain tracking in web contexts.</li>
                </ul>
                <p className="mt-2">
                  Where required by law, we will obtain your consent before using non-essential cookies or similar technologies.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">5. Payments</h3>
                <p>
                  If you make a purchase or subscribe to paid features, payment information (such as card details and billing information) is collected and processed directly by third-party payment providers (for example, Stripe, PayPal, or the relevant app store provider). We do not store full payment card numbers on our servers.
                </p>
                <p className="mt-2">
                  Your use of those payment services is governed by their own terms and privacy policies in addition to this Privacy Policy.
                </p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">6. Data Retention</h3>
                <p>We retain information as long as necessary to provide the Service, comply with legal obligations, and resolve disputes. When you delete your account from within the ForeScore app, we permanently remove your personal profile and associated gameplay data, except for information we are legally required or have a legitimate business reason to retain (for example, basic transaction records for accounting).</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">7. Your Rights & Choices</h3>
                <p>Depending on your location, you may have the right to:</p>
                <ul className="list-disc list-inside mt-2 space-y-1">
                  <li>Access or request a copy of your data.</li>
                  <li>Correct or delete personal data.</li>
                  <li>Restrict or object to our processing of your data.</li>
                  <li>Withdraw consent for marketing communications at any time by clicking "unsubscribe" in an email or adjusting settings in your account.</li>
                </ul>
                <p className="mt-2">You can delete your ForeScore account at any time directly from within the iOS app. For other rights requests, email us at support@forescore.xyz.</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">8. Security</h3>
                <p>We use reasonable technical, administrative, and organizational safeguards designed to protect your information from unauthorized access, use, alteration, or destruction. However, no system is completely secure, and we cannot guarantee the absolute security of your data. You are responsible for maintaining the confidentiality of your account credentials and for any activity under your account.</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">9. Children's Privacy</h3>
                <p>The Service is not directed to children under 13, and we do not knowingly collect personal data from children under 13 (or under the minimum digital age of consent in your jurisdiction). If you believe a child has provided us with personal data in violation of this Policy, please contact us so we can take appropriate steps to delete such information.</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">10. International Users</h3>
                <p>ForeScore is based in the United States, and your information may be processed and stored in the U.S. and other countries where our service providers operate. These countries may have data protection laws that differ from those in your jurisdiction.</p>
                <p className="mt-2">Where required, we rely on appropriate legal bases and safeguards for transferring personal data, such as your consent, performance of a contract, or other mechanisms recognized under applicable data protection laws.</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">11. Changes to this Policy</h3>
                <p>We may update this Privacy Policy from time to time to reflect changes in our practices, technologies, or legal requirements. If changes are material, we will notify you via the Service, email, or other reasonable means. The updated Policy will have an updated "Last updated" date. Your continued use of the Service after the Policy becomes effective means you accept the updated terms. If you do not agree, you should stop using the Service.</p>
              </section>

              <section>
                <h3 className="font-semibold text-lg mb-2">12. Contact Us</h3>
                <p>If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, you can contact us at:</p>
                <p className="mt-2">
                  danoNano, LLC dba ForeScore<br />
                  Email: support@forescore.xyz<br />
                  Postal: 2447 E Fremont Rd, Phoenix, AZ 85042, USA
                </p>
              </section>

              <div className="text-xs text-gray-500 mt-6 pt-4 border-t">
                <p>Last updated: September 25, 2025</p>
              </div>
            </div>
          </ScrollArea>
        </DialogContent>
      </Dialog>
    </>
  );
}